apiVersion: v1
kind: Service
metadata:
  name: lattice
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: lattice
  ports:
    - protocol: TCP
      port: {{ .Values.lattice.service.port }}
      targetPort: {{ .Values.lattice.service.port }}
