apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: mcp-server
  ports:
    - protocol: TCP
      port: {{ .Values.mcpServer.service.port }}
      targetPort: {{ .Values.mcpServer.service.port }}
