apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nre-agent-approvals
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: {{ .Values.nreAgent.persistence.size }}
