apiVersion: apps/v1
kind: Deployment
metadata:
  name: nre-agent
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.nreAgent.replicaCount }}
  selector:
    matchLabels:
      app: nre-agent
  template:
    metadata:
      labels:
        app: nre-agent
    spec:
      containers:
        - name: nre-agent
          image: "{{ .Values.nreAgent.image.repository }}:{{ .Values.nreAgent.image.tag }}"
          imagePullPolicy: {{ .Values.nreAgent.image.pullPolicy }}
          env:
            - name: NRE_AGENT_SCENARIO
              value: "{{ .Values.nreAgent.env.NRE_AGENT_SCENARIO }}"
            - name: NRE_AGENT_INTERVAL_SECONDS
              value: "{{ .Values.nreAgent.env.NRE_AGENT_INTERVAL_SECONDS }}"
          resources:
            {{- toYaml .Values.nreAgent.resources | nindent 12 }}
